// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories.get').default>>>>
    }
    '/api/chats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chats/index.get').default>>>>
    }
    '/api/moderate-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/moderate-image.post').default>>>>
    }
    '/api/moderate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/moderate.post').default>>>>
    }
    '/api/products/attach': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/attach.post').default>>>>
    }
    '/api/products/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/create.post').default>>>>
    }
    '/api/products/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/search.get').default>>>>
    }
    '/api/tracking/:trackingCode': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tracking/[trackingCode].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@3.20.2_d_255905f2bba5285428a83f8fd4c113b7/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}