// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at ۱۴۰۵/۴/۶, ۱۵:۰۰:۰۰
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/apps/dampezeshki/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/apps/dampezeshki/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/shared/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/apps/dampezeshki/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/apps/dampezeshki/plugins/**/*.{js,ts,mjs}","C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/apps/dampezeshki/composables/**/*.{js,ts,mjs}","C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/apps/dampezeshki/utils/**/*.{js,ts,mjs}","C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/apps/dampezeshki/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/apps/dampezeshki/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/apps/dampezeshki/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/School/Desktop/FrontendFramework/nuxtjs/projects/PetomanFront/apps/dampezeshki/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;