
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AppFooter: typeof import("../components/AppFooter.vue").default
export const CategorySelector: typeof import("../components/CategorySelector.vue").default
export const GlobalToast: typeof import("../components/GlobalToast.vue").default
export const MedicineCategorySelector: typeof import("../components/MedicineCategorySelector.vue").default
export const MedicineSEOBuilder: typeof import("../components/MedicineSEOBuilder.vue").default
export const MedicineSearchOrCreate: typeof import("../components/MedicineSearchOrCreate.vue").default
export const MedicinesList: typeof import("../components/MedicinesList.vue").default
export const OrderDetailsModal: typeof import("../components/OrderDetailsModal.vue").default
export const PatientCallOverlay: typeof import("../components/PatientCallOverlay.vue").default
export const PersianCalendar: typeof import("../components/PersianCalendar.vue").default
export const PersianDatePicker: typeof import("../components/PersianDatePicker.vue").default
export const ProductOrderDetailsModal: typeof import("../components/ProductOrderDetailsModal.vue").default
export const ProductSEOBuilder: typeof import("../components/ProductSEOBuilder.vue").default
export const ProductSearchOrCreate: typeof import("../components/ProductSearchOrCreate.vue").default
export const ProductTitleInput: typeof import("../components/ProductTitleInput.vue").default
export const ProductVideoUploader: typeof import("../components/ProductVideoUploader.vue").default
export const ProductsList: typeof import("../components/ProductsList.vue").default
export const AddAddressSheet: typeof import("../components/address/AddAddressSheet.vue").default
export const AddressListSheet: typeof import("../components/address/AddressListSheet.vue").default
export const AddressSelectionSheet: typeof import("../components/address/AddressSelectionSheet.vue").default
export const PharmacyDetailsCard: typeof import("../components/cards/PharmacyDetailsCard.vue").default
export const ClinicCard: typeof import("../components/clinic/ClinicCard.vue").default
export const MapSearchField: typeof import("../components/clinic/MapSearchField.vue").default
export const CitySelector: typeof import("../components/header/CitySelector.vue").default
export const SiteHeader: typeof import("../components/header/SiteHeader.vue").default
export const SiteHeaderBackup: typeof import("../components/header/SiteHeader_backup.vue").default
export const AdditionalServiceCard: typeof import("../components/home/AdditionalServiceCard.vue").default
export const AiVetWidget: typeof import("../components/home/AiVetWidget.vue").default
export const CTASection: typeof import("../components/home/CTASection.vue").default
export const EmergencyBanner: typeof import("../components/home/EmergencyBanner.vue").default
export const FeatureCard: typeof import("../components/home/FeatureCard.vue").default
export const FeaturesSection: typeof import("../components/home/FeaturesSection.vue").default
export const Hero: typeof import("../components/home/Hero.vue").default
export const HeroSection: typeof import("../components/home/HeroSection.vue").default
export const ServiceCard: typeof import("../components/home/ServiceCard.vue").default
export const ServicesRow: typeof import("../components/home/ServicesRow.vue").default
export const ServicesSection: typeof import("../components/home/ServicesSection.vue").default
export const TestimonialCard: typeof import("../components/home/TestimonialCard.vue").default
export const TestimonialsSection: typeof import("../components/home/TestimonialsSection.vue").default
export const CardSkeleton: typeof import("../components/pharmacy/CardSkeleton.vue").default
export const CartWidget: typeof import("../components/pharmacy/CartWidget.vue").default
export const MapboxAddressSelector: typeof import("../components/pharmacy/MapboxAddressSelector.vue").default
export const PharmacyCardOld: typeof import("../components/pharmacy/PharmacyCard-old.vue").default
export const PharmacyCard: typeof import("../components/pharmacy/PharmacyCard.vue").default
export const PharmacyCartWidget: typeof import("../components/pharmacy/PharmacyCartWidget.vue").default
export const PharmacyPageSkeleton: typeof import("../components/pharmacy/PharmacyPageSkeleton.vue").default
export const PharmacySliderCard: typeof import("../components/pharmacy/PharmacySliderCard.vue").default
export const Avatar: typeof import("../components/ui/Avatar.vue").default
export const Badge: typeof import("../components/ui/Badge.vue").default
export const Button: typeof import("../components/ui/Button.vue").default
export const Card: typeof import("../components/ui/Card.vue").default
export const CityModal: typeof import("../components/ui/CityModal.vue").default
export const Dropdown: typeof import("../components/ui/Dropdown.vue").default
export const FileUploadCard: typeof import("../components/ui/FileUploadCard.vue").default
export const Input: typeof import("../components/ui/Input.vue").default
export const Modal: typeof import("../components/ui/Modal.vue").default
export const Notification: typeof import("../components/ui/Notification.vue").default
export const PersianTimePicker: typeof import("../components/ui/PersianTimePicker.vue").default
export const Select: typeof import("../components/ui/Select.vue").default
export const Skeleton: typeof import("../components/ui/Skeleton.vue").default
export const USelectMenu: typeof import("../components/ui/USelectMenu.vue").default
export const VetCard: typeof import("../components/vet/VetCard.vue").default
export const AddressSelector: typeof import("../../../shared/components/AddressSelector.vue").default
export const MapCitySelector: typeof import("../../../shared/components/MapCitySelector.vue").default
export const NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
export const NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
export const NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyAppFooter: LazyComponent<typeof import("../components/AppFooter.vue").default>
export const LazyCategorySelector: LazyComponent<typeof import("../components/CategorySelector.vue").default>
export const LazyGlobalToast: LazyComponent<typeof import("../components/GlobalToast.vue").default>
export const LazyMedicineCategorySelector: LazyComponent<typeof import("../components/MedicineCategorySelector.vue").default>
export const LazyMedicineSEOBuilder: LazyComponent<typeof import("../components/MedicineSEOBuilder.vue").default>
export const LazyMedicineSearchOrCreate: LazyComponent<typeof import("../components/MedicineSearchOrCreate.vue").default>
export const LazyMedicinesList: LazyComponent<typeof import("../components/MedicinesList.vue").default>
export const LazyOrderDetailsModal: LazyComponent<typeof import("../components/OrderDetailsModal.vue").default>
export const LazyPatientCallOverlay: LazyComponent<typeof import("../components/PatientCallOverlay.vue").default>
export const LazyPersianCalendar: LazyComponent<typeof import("../components/PersianCalendar.vue").default>
export const LazyPersianDatePicker: LazyComponent<typeof import("../components/PersianDatePicker.vue").default>
export const LazyProductOrderDetailsModal: LazyComponent<typeof import("../components/ProductOrderDetailsModal.vue").default>
export const LazyProductSEOBuilder: LazyComponent<typeof import("../components/ProductSEOBuilder.vue").default>
export const LazyProductSearchOrCreate: LazyComponent<typeof import("../components/ProductSearchOrCreate.vue").default>
export const LazyProductTitleInput: LazyComponent<typeof import("../components/ProductTitleInput.vue").default>
export const LazyProductVideoUploader: LazyComponent<typeof import("../components/ProductVideoUploader.vue").default>
export const LazyProductsList: LazyComponent<typeof import("../components/ProductsList.vue").default>
export const LazyAddAddressSheet: LazyComponent<typeof import("../components/address/AddAddressSheet.vue").default>
export const LazyAddressListSheet: LazyComponent<typeof import("../components/address/AddressListSheet.vue").default>
export const LazyAddressSelectionSheet: LazyComponent<typeof import("../components/address/AddressSelectionSheet.vue").default>
export const LazyPharmacyDetailsCard: LazyComponent<typeof import("../components/cards/PharmacyDetailsCard.vue").default>
export const LazyClinicCard: LazyComponent<typeof import("../components/clinic/ClinicCard.vue").default>
export const LazyMapSearchField: LazyComponent<typeof import("../components/clinic/MapSearchField.vue").default>
export const LazyCitySelector: LazyComponent<typeof import("../components/header/CitySelector.vue").default>
export const LazySiteHeader: LazyComponent<typeof import("../components/header/SiteHeader.vue").default>
export const LazySiteHeaderBackup: LazyComponent<typeof import("../components/header/SiteHeader_backup.vue").default>
export const LazyAdditionalServiceCard: LazyComponent<typeof import("../components/home/AdditionalServiceCard.vue").default>
export const LazyAiVetWidget: LazyComponent<typeof import("../components/home/AiVetWidget.vue").default>
export const LazyCTASection: LazyComponent<typeof import("../components/home/CTASection.vue").default>
export const LazyEmergencyBanner: LazyComponent<typeof import("../components/home/EmergencyBanner.vue").default>
export const LazyFeatureCard: LazyComponent<typeof import("../components/home/FeatureCard.vue").default>
export const LazyFeaturesSection: LazyComponent<typeof import("../components/home/FeaturesSection.vue").default>
export const LazyHero: LazyComponent<typeof import("../components/home/Hero.vue").default>
export const LazyHeroSection: LazyComponent<typeof import("../components/home/HeroSection.vue").default>
export const LazyServiceCard: LazyComponent<typeof import("../components/home/ServiceCard.vue").default>
export const LazyServicesRow: LazyComponent<typeof import("../components/home/ServicesRow.vue").default>
export const LazyServicesSection: LazyComponent<typeof import("../components/home/ServicesSection.vue").default>
export const LazyTestimonialCard: LazyComponent<typeof import("../components/home/TestimonialCard.vue").default>
export const LazyTestimonialsSection: LazyComponent<typeof import("../components/home/TestimonialsSection.vue").default>
export const LazyCardSkeleton: LazyComponent<typeof import("../components/pharmacy/CardSkeleton.vue").default>
export const LazyCartWidget: LazyComponent<typeof import("../components/pharmacy/CartWidget.vue").default>
export const LazyMapboxAddressSelector: LazyComponent<typeof import("../components/pharmacy/MapboxAddressSelector.vue").default>
export const LazyPharmacyCardOld: LazyComponent<typeof import("../components/pharmacy/PharmacyCard-old.vue").default>
export const LazyPharmacyCard: LazyComponent<typeof import("../components/pharmacy/PharmacyCard.vue").default>
export const LazyPharmacyCartWidget: LazyComponent<typeof import("../components/pharmacy/PharmacyCartWidget.vue").default>
export const LazyPharmacyPageSkeleton: LazyComponent<typeof import("../components/pharmacy/PharmacyPageSkeleton.vue").default>
export const LazyPharmacySliderCard: LazyComponent<typeof import("../components/pharmacy/PharmacySliderCard.vue").default>
export const LazyAvatar: LazyComponent<typeof import("../components/ui/Avatar.vue").default>
export const LazyBadge: LazyComponent<typeof import("../components/ui/Badge.vue").default>
export const LazyButton: LazyComponent<typeof import("../components/ui/Button.vue").default>
export const LazyCard: LazyComponent<typeof import("../components/ui/Card.vue").default>
export const LazyCityModal: LazyComponent<typeof import("../components/ui/CityModal.vue").default>
export const LazyDropdown: LazyComponent<typeof import("../components/ui/Dropdown.vue").default>
export const LazyFileUploadCard: LazyComponent<typeof import("../components/ui/FileUploadCard.vue").default>
export const LazyInput: LazyComponent<typeof import("../components/ui/Input.vue").default>
export const LazyModal: LazyComponent<typeof import("../components/ui/Modal.vue").default>
export const LazyNotification: LazyComponent<typeof import("../components/ui/Notification.vue").default>
export const LazyPersianTimePicker: LazyComponent<typeof import("../components/ui/PersianTimePicker.vue").default>
export const LazySelect: LazyComponent<typeof import("../components/ui/Select.vue").default>
export const LazySkeleton: LazyComponent<typeof import("../components/ui/Skeleton.vue").default>
export const LazyUSelectMenu: LazyComponent<typeof import("../components/ui/USelectMenu.vue").default>
export const LazyVetCard: LazyComponent<typeof import("../components/vet/VetCard.vue").default>
export const LazyAddressSelector: LazyComponent<typeof import("../../../shared/components/AddressSelector.vue").default>
export const LazyMapCitySelector: LazyComponent<typeof import("../../../shared/components/MapCitySelector.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
export const LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
export const LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher_1b0924509a43a951d99fe8c84250ca65/node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
